/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.glucode.news.search.api;

import com.glucode.news.search.model.Message;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2024-08-31T21:23:06.156+02:00")

@Validated
@Api(value = "search", description = "the search API")
@RequestMapping(value = "/api")
public interface SearchApi {

    @ApiOperation(value = "Get message", nickname = "searchGet", notes = "", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A successful response", response = String.class) })
    @RequestMapping(value = "/search",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> searchGet();


    @ApiOperation(value = "Post message", nickname = "searchPost", notes = "", response = String.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A successful response with message", response = String.class) })
    @RequestMapping(value = "/search",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<String> searchPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Message message);

}
